language: android
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository

before_script:
  - echo y | android update sdk --no-ui --filter platform-tool

script:
  - ./gradlew build

after_failure:
  - cat $HOME/build/piruin/phototaker/phototaker/build/outputs/lint-results-debug.xml

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  on:
      tags: true
